config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/, defaults: {locale: "en"} do
    resources :translations
  end

  root to: 'translations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/translation.rb
class Translation < ApplicationRecord
  mount_uploader :image, ImageUploader
  translates :value

  validates_presence_of :key
  validates_uniqueness_of :key

  default_scope { order(:key) }

  def computed_value
    image.url || value
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @q = Translation.with_translations(I18n.locale).ransack(params[:q])
    @translations = @q.result(distinct: true).page(params[:page]).per(20)
  end

  def new
    @translation = Translation.new
  end

  def create
    @translation = Translation.new secure_params
    if @translation.save
      redirect_to translations_path(locale: I18n.locale)
    else
      render :new
    end
  end

  def edit
    @translation = Translation.find params[:id]
  end

  def update
    @translation = Translation.find params[:id]
    if @translation.update secure_params
      redirect_to translations_path(locale: I18n.locale)
    else
      render :edit
    end
  end

  def destroy
    @translation = Translation.find params[:id]
    @translation.destroy
    redirect_to translations_path(locale: I18n.locale)
  end

  private

  def secure_params
    params.require(:translation).permit(:key, :value, :image, :remove_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def paginate objects, options = {}
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )

    super( objects, options )
  end
end

app/views/application/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Translation Backend', root_path(locale: I18n.locale), class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= I18n.locale %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% I18n.available_locales.reject { |l| l == I18n.locale }.each do |l| %>
            <li><%= link_to l, translations_path(locale: l) %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete %>
            </li>
          </ul>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TranslationBackend</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'navigation' %>
  <div class="container">

    <%= yield %>
  </div>
</body>
</html>

app/views/translations/_form.html.erb
<%= simple_form_for @translation, url: @translation.new_record? ? translations_path(locale: I18n.locale) : translation_path(locale: I18n.locale) do |f| %>
    <%= f.input :key %>

    <% if @translation.image.present? %>
        <div>
          <%= image_tag @translation.image.url, width: 300 %>
          <div class="form-group">
            <label>

              <%= f.check_box :remove_image %>
              <%= t('.remove_image') %>
            </label>
          </div>

        </div>
    <% else %>
        <%= f.input :value %>
        <%= f.input :image %>
    <% end %>

    <%= f.button :submit %>
<% end %>

app/views/translations/_translation.html.erb
<tr>
  <td class="nowrap"><code><%= translation.key %></code></td>
  <td class="stretch">
    <%= fa_icon('image') if translation.image.present? %>
    <%= translation.computed_value %>
  </td>
  <td class="nowrap"><%= link_to t('.remove'), translation_path(translation, locale: I18n.locale), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %></td>
  <td class="nowrap"><%= link_to t('.edit'), edit_translation_path(translation, locale: I18n.locale), class: 'btn btn-xs btn-info' %></td>
</tr>

app/views/translations/edit.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>

app/views/translations/index.html.erb
<h2><%= t('.title') %></h2>

<div class="row">
  <div class="col-md-6">
    <%= link_to t('.create_new'), new_translation_path(locale: I18n.locale), class: 'btn btn-primary' %>
  </div>
  <div class="col-md-6 text-right">
    <%= search_form_for @q, class: 'form-inline' do |f| %>
        <div class="form-group">
          <%= f.search_field :key_cont, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.submit t('.search'), class: 'btn'%>
        </div>
    <% end %>

  </div>
</div>



<table class="table table-striped">
  <thead>
  <tr>
    <th><%= t('activerecord.attributes.translation.key') %></th>
    <th><%= t('activerecord.attributes.translation.value') %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <%= render @translations %>
  </tbody>
</table>

<%= paginate @translations %>

app/views/translations/new.html.erb
<h2><%= t('.title') %></h2>

<%= render 'form' %>